# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20170703_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
