# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='doenload',
            new_name='download',
        ),
    ]
